name: deploy-auth

on: # when to run this workflow
  push:
    branches:
      # pushes to master will trigger this workflow, can list more branches as well
      - master
    paths:
      # only on pushes to auth app
      - 'packages/auth/**'

defaults:
  run:
    # sets execution environment inside auth app
    # npm run build, start, etc will all run here
    working-directory: packages/auth

jobs:
  build:
    runs-on: ubuntu-latest # linux based vm

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2 # gives access to aws cli
      # sync dist directory from build command with s3 bucket
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME}}/auth/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      # automated invalidation so aws updates with latest webpack chunk file
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/auth/latest/remoteEntry.js"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
